#!/usr/bin/env python3
"""Shared library for the FHCP steelman audit PDF (Report route, ReportLab).

English document: FreeSerif family (registered with all 4 weights),
DejaVuSans for symbols. Palette from `pdf.py palette.cascade` (seed 7).
Body 10.5pt justified, H1 22pt with accent rule, H2 15pt, H3 11.5pt.
"""
import os
import sys
import hashlib

PDF_SKILL_DIR = '/home/z/my-project/skills/pdf'
_scripts = os.path.join(PDF_SKILL_DIR, 'scripts')
if _scripts not in sys.path:
    sys.path.insert(0, _scripts)

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY, TA_RIGHT
from reportlab.lib.styles import ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle,
    KeepTogether, CondPageBreak, HRFlowable, Flowable,
)
from reportlab.platypus.tableofcontents import TableOfContents
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily

# ━━ Fonts ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
FONT_DIR = '/usr/share/fonts'

pdfmetrics.registerFont(TTFont('NotoSerifSC', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Regular.ttf'))
pdfmetrics.registerFont(TTFont('NotoSerifSC-Bold', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Bold.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif', f'{FONT_DIR}/truetype/freefont/FreeSerif.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Bold', f'{FONT_DIR}/truetype/freefont/FreeSerifBold.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Italic', f'{FONT_DIR}/truetype/freefont/FreeSerifItalic.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-BoldItalic', f'{FONT_DIR}/truetype/freefont/FreeSerifBoldItalic.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSans', f'{FONT_DIR}/truetype/dejavu/DejaVuSansMono.ttf'))

registerFontFamily('NotoSerifSC', normal='NotoSerifSC', bold='NotoSerifSC-Bold')
registerFontFamily('FreeSerif', normal='FreeSerif', bold='FreeSerif-Bold',
                   italic='FreeSerif-Italic', boldItalic='FreeSerif-BoldItalic')
registerFontFamily('DejaVuSans', normal='DejaVuSans', bold='DejaVuSans')

from pdf import install_font_fallback  # noqa: E402  (skill helper)
install_font_fallback()

# ━━ Cascade Palette (auto-generated by design_engine.py palette-cascade) ━━
PAGE_BG       = colors.HexColor('#f1f0ef')
SECTION_BG    = colors.HexColor('#f2f1f0')
CARD_BG       = colors.HexColor('#e8e7e4')
TABLE_STRIPE  = colors.HexColor('#eeedeb')
HEADER_FILL   = colors.HexColor('#504933')
COVER_BLOCK   = colors.HexColor('#867b5a')
BORDER        = colors.HexColor('#cfcab8')
ICON          = colors.HexColor('#8c7e52')
ACCENT        = colors.HexColor('#87702a')
ACCENT_2      = colors.HexColor('#3a95b4')
TEXT_PRIMARY  = colors.HexColor('#1c1c1a')
TEXT_MUTED    = colors.HexColor('#78766f')

TABLE_HEADER_COLOR = HEADER_FILL
TABLE_HEADER_TEXT  = colors.white
TABLE_ROW_EVEN     = colors.white
TABLE_ROW_ODD      = TABLE_STRIPE

# ━━ Page geometry ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PAGE_W, PAGE_H = A4
MARGIN = 1.0 * inch          # symmetric margins (iron rule)
AVAIL_W = PAGE_W - 2 * MARGIN
AVAIL_H = PAGE_H - 2 * MARGIN
H1_ORPHAN_THRESHOLD = AVAIL_H * 0.25
MAX_KEEP_HEIGHT = PAGE_H * 0.4

DOC_TITLE = 'The Fundamental Higher Consciousness Premise: A Steelman Audit and Consolidation'
DOC_AUTHOR = 'Z.ai'

# ━━ Styles ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
S = {}
S['body'] = ParagraphStyle('Body', fontName='FreeSerif', fontSize=10.5,
                           leading=16.5, alignment=TA_JUSTIFY,
                           textColor=TEXT_PRIMARY, spaceBefore=0, spaceAfter=10)
S['body_first'] = ParagraphStyle('BodyFirst', parent=S['body'])
S['h1'] = ParagraphStyle('H1', fontName='FreeSerif', fontSize=22, leading=27,
                         alignment=TA_LEFT, textColor=TEXT_PRIMARY,
                         spaceBefore=6, spaceAfter=4)
S['h2'] = ParagraphStyle('H2', fontName='FreeSerif', fontSize=15, leading=20,
                         alignment=TA_LEFT, textColor=HEADER_FILL,
                         spaceBefore=16, spaceAfter=8)
S['h3'] = ParagraphStyle('H3', fontName='FreeSerif', fontSize=11.5, leading=16,
                         alignment=TA_LEFT, textColor=TEXT_PRIMARY,
                         spaceBefore=12, spaceAfter=6)
S['quote'] = ParagraphStyle('Quote', fontName='FreeSerif-Italic', fontSize=10.5,
                            leading=16.5, alignment=TA_LEFT,
                            textColor=TEXT_PRIMARY, spaceBefore=0, spaceAfter=0)
S['quote_attr'] = ParagraphStyle('QuoteAttr', fontName='FreeSerif', fontSize=8.5,
                                 leading=12, alignment=TA_LEFT,
                                 textColor=TEXT_MUTED, spaceBefore=4)
S['callout'] = ParagraphStyle('Callout', fontName='FreeSerif', fontSize=10,
                              leading=15.5, alignment=TA_LEFT,
                              textColor=TEXT_PRIMARY)
S['caption'] = ParagraphStyle('Caption', fontName='FreeSerif', fontSize=8.5,
                              leading=12, alignment=TA_CENTER,
                              textColor=TEXT_MUTED, spaceBefore=0, spaceAfter=0)
S['th'] = ParagraphStyle('TH', fontName='FreeSerif', fontSize=9,
                         leading=12.5, alignment=TA_LEFT,
                         textColor=colors.white)
S['td'] = ParagraphStyle('TD', fontName='FreeSerif', fontSize=8.8,
                         leading=12.2, alignment=TA_LEFT,
                         textColor=TEXT_PRIMARY)
S['td_c'] = ParagraphStyle('TDC', parent=S['td'], alignment=TA_CENTER)
S['toc_title'] = ParagraphStyle('TocTitle', fontName='FreeSerif', fontSize=22,
                                leading=27, alignment=TA_LEFT,
                                textColor=TEXT_PRIMARY, spaceAfter=18)
S['toc0'] = ParagraphStyle('TOC0', fontName='FreeSerif', fontSize=11.5,
                           leading=20, leftIndent=0, textColor=TEXT_PRIMARY)
S['toc1'] = ParagraphStyle('TOC1', fontName='FreeSerif', fontSize=10,
                           leading=16, leftIndent=22, textColor=TEXT_MUTED)

# ━━ Doc template with TOC + zone-aware footer ━━━━━━━━━━━━━━━━━━━━━━━━━━━
class BodyStartMarker(Flowable):
    """Zero-size marker: records the page where body content begins."""
    def __init__(self):
        Flowable.__init__(self)
        self.width = 0
        self.height = 0

    def wrap(self, aw, ah):
        return (0, 0)

    def draw(self):
        pass


class TocDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if isinstance(flowable, BodyStartMarker):
            self._body_start = self.page
            return
        if hasattr(flowable, 'bookmark_name'):
            level = getattr(flowable, 'bookmark_level', 0)
            text = getattr(flowable, 'bookmark_text', '')
            key = getattr(flowable, 'bookmark_key', '')
            # Report the DISPLAYED page number (arabic body numbering),
            # so TOC entries match the printed footers.
            body_start = getattr(self, '_body_start', None)
            if body_start is not None and self.page >= body_start:
                page = self.page - body_start + 1
            else:
                page = self.page
            self.notify('TOCEntry', (level, text, page, key))


_ROMAN = {1: 'i', 2: 'ii', 3: 'iii', 4: 'iv', 5: 'v', 6: 'vi', 7: 'vii',
          8: 'viii', 9: 'ix', 10: 'x', 11: 'xi', 12: 'xii'}


def paint_page(canvas, doc):
    """Header + footer painter: roman for front matter, arabic for body."""
    canvas.saveState()
    # Header: doc title left, accent rule under it
    canvas.setFont('FreeSerif', 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(MARGIN, PAGE_H - 0.62 * inch, 'The Fundamental Higher Consciousness Premise')
    canvas.drawRightString(PAGE_W - MARGIN, PAGE_H - 0.62 * inch, 'Steelman Audit and Consolidation')
    canvas.setStrokeColor(ACCENT)
    canvas.setLineWidth(1.2)
    canvas.line(MARGIN, PAGE_H - 0.70 * inch, PAGE_W - MARGIN, PAGE_H - 0.70 * inch)
    # Footer: light rule + author left + bare page number right
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(0.5)
    canvas.line(MARGIN, 0.62 * inch, PAGE_W - MARGIN, 0.62 * inch)
    canvas.setFont('FreeSerif', 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(MARGIN, 0.44 * inch, DOC_AUTHOR)
    body_start = getattr(doc, '_body_start', None)
    if body_start is None or doc.page < body_start:
        label = _ROMAN.get(doc.page, str(doc.page))
    else:
        label = str(doc.page - body_start + 1)
    canvas.drawRightString(PAGE_W - MARGIN, 0.44 * inch, label)
    canvas.restoreState()


# ━━ Builders ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
def _nb_dash(text):
    """Bind spaced em-dashes to the preceding word.

    Replaces the breakable space before an em-dash with a non-breaking
    space, so a dash can never start a line (typography hygiene).
    """
    return text.replace(' \u2014', '\u00a0\u2014')


def _bookmark(text, style, level):
    key = 'h_' + hashlib.md5(text.encode()).hexdigest()[:8]
    p = Paragraph('<a name="%s"/>%s' % (key, text), style)
    p.bookmark_name = key
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    return p


def h1(story, text):
    """Major section heading with accent underline; orphan-protected."""
    story.append(CondPageBreak(H1_ORPHAN_THRESHOLD))
    head = _bookmark('<b>%s</b>' % text, S['h1'], 0)
    rule = HRFlowable(width='100%', thickness=1.6, color=ACCENT,
                      spaceBefore=0, spaceAfter=14)
    story.append(KeepTogether([head, rule]))


def h2(story, text):
    story.append(CondPageBreak(0.09 * AVAIL_H))
    story.append(_bookmark('<b>%s</b>' % text, S['h2'], 1))


def h3(story, text):
    story.append(CondPageBreak(0.07 * AVAIL_H))
    story.append(Paragraph('<b>%s</b>' % text, S['h3']))


def body(story, text):
    story.append(Paragraph(_nb_dash(text), S['body']))


def bullet(story, text):
    style = ParagraphStyle('Bullet', parent=S['body'], leftIndent=16,
                           bulletIndent=4, spaceAfter=6)
    story.append(Paragraph(_nb_dash(text), style, bulletText='\u2022'))


def quote(story, text, attr=None):
    """Block quote: italic, indented, muted accent left border."""
    rows = [[Paragraph(_nb_dash(text), S['quote'])]]
    if attr:
        rows.append([Paragraph(attr, S['quote_attr'])])
    tbl = Table(rows, colWidths=[AVAIL_W - 24], hAlign='CENTER')
    tbl.setStyle(TableStyle([
        ('LINEBEFORE', (0, 0), (0, -1), 2, ACCENT),
        ('LEFTPADDING', (0, 0), (-1, -1), 14),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (0, 0), 2),
        ('BOTTOMPADDING', (0, -1), (0, -1), 2),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
    ]))
    story.append(Spacer(1, 6))
    story.append(tbl)
    story.append(Spacer(1, 10))


def callout(story, title, text):
    """Callout box: accent left border + light tint background."""
    inner = []
    if title:
        inner.append(Paragraph('<b>%s</b>' % title, S['callout']))
        inner.append(Spacer(1, 3))
    inner.append(Paragraph(_nb_dash(text), S['callout']))
    box = Table([[inner]], colWidths=[AVAIL_W * 0.94], hAlign='CENTER')
    box.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), CARD_BG),
        ('LINEBEFORE', (0, 0), (0, -1), 3, ACCENT),
        ('LEFTPADDING', (0, 0), (-1, -1), 12),
        ('RIGHTPADDING', (0, 0), (-1, -1), 12),
        ('TOPPADDING', (0, 0), (-1, -1), 9),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 9),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
    ]))
    story.append(Spacer(1, 8))
    story.append(box)
    story.append(Spacer(1, 12))


def data_table(story, caption, headers, rows, ratios, font_size=8.8,
               header_font=9.0, center_cols=()):
    """Standard data table: Paragraph cells, palette colors, centered.

    ratios must sum to ~1.0; widths scaled to 100% of available width.
    """
    assert abs(sum(ratios) - 1.0) < 0.01, 'ratios must sum to 1.0'
    col_widths = [r * AVAIL_W for r in ratios]
    assert sum(col_widths) <= AVAIL_W + 0.5

    th_style = ParagraphStyle('THx', parent=S['th'], fontSize=header_font,
                              leading=header_font + 3.5)
    td_style = ParagraphStyle('TDx', parent=S['td'], fontSize=font_size,
                              leading=font_size + 3.4)
    td_c_style = ParagraphStyle('TDCx', parent=td_style, alignment=TA_CENTER)

    data = [[Paragraph('<b>%s</b>' % h, th_style) for h in headers]]
    for row in rows:
        cells = []
        for ci, cell in enumerate(row):
            st = td_c_style if ci in center_cols else td_style
            cells.append(Paragraph(_nb_dash(cell), st))
        data.append(cells)

    tbl = Table(data, colWidths=col_widths, hAlign='CENTER', repeatRows=1)
    style_cmds = [
        ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ('TEXTCOLOR', (0, 0), (-1, 0), TABLE_HEADER_TEXT),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('GRID', (0, 0), (-1, -1), 0.5, BORDER),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
    ]
    for i in range(1, len(data)):
        bg = TABLE_ROW_ODD if i % 2 == 1 else TABLE_ROW_EVEN
        style_cmds.append(('BACKGROUND', (0, i), (-1, i), bg))
    tbl.setStyle(TableStyle(style_cmds))

    story.append(Spacer(1, 16))
    if len(rows) <= 12:
        story.append(KeepTogether([tbl, Spacer(1, 6),
                                    Paragraph(caption, S['caption'])]))
    else:
        story.append(tbl)
        story.append(Spacer(1, 6))
        story.append(Paragraph(caption, S['caption']))
    story.append(Spacer(1, 16))


def safe_keep_together(elements):
    total_h = 0
    for el in elements:
        w, h = el.wrap(AVAIL_W, PAGE_H)
        total_h += h
    if total_h <= MAX_KEEP_HEIGHT:
        return [KeepTogether(elements)]
    elif len(elements) >= 2:
        return [KeepTogether(elements[:2])] + list(elements[2:])
    return list(elements)
