#!/usr/bin/env python3
"""Sixth Edition (Audited Edition), Part 2: chapters 3-4.

Chapter 3 extends the corpus arc to the culmination. Chapter 4 consolidates
the non-dual culmination arc itself (ds4 turns 89-106): the unfalsifiability
concession, the classical-theism fork, death as perspective-shattering, the
necessity move and its ceiling, the decombination demotion, the formalization
boundary, and the final position on mathematics.
"""
import fhcp_pdf_lib as L


def add_content(story):
    # ==================== 3. THE ARC OF THE CORPUS ====================
    L.h1(story, '3. The Arc of the Corpus, Extended')

    L.body(story,
           'The corpus arc now terminates in a five-way structure. The '
           'dialogue line produced the framework; the '
           'external-exchange line formalized, critiqued, and \u2014 new '
           'in this round \u2014 culminated it; the audit lineage '
           'consolidated it; the adversarial external audit stress-tested '
           'its claim discipline; and the empirical source set anchored '
           'its research program. The culmination is the newest movement: '
           'the DeepSeek main line\u2019s final eighteen turns, which '
           'begin from the eliminative program\u2019s settled state and '
           'end in the strictly non-dual position. The movement has a '
           'clear anatomy. The interlocutor asks whether physics or '
           'empirical science negates the non-dual only-Absolute '
           'version, and the counterpart concedes that nothing does '
           '\u2014 the framework is empirically unfalsifiable. The '
           'interlocutor then argues that duality cannot be objectively '
           'true (an ultimate cannot be composed), and the counterpart '
           'grants the argument but insists it proves only monism, '
           'leaving a menu of monisms. The interlocutor eliminates the '
           'menu item by item \u2014 classical theism\u2019s God-plus-'
           'creatures complex truth is rejected as defiance of '
           'completeness, and the counterpart\u2019s defense (complete '
           'means lacking nothing in its own nature, not being the only '
           'thing that exists) is overruled by the interlocutor\u2019s '
           'stipulation that complete means exclusive totality. The '
           'counterpart\u2019s final position is the full concession: '
           'under the interlocutor\u2019s constraints, classical theism '
           'is incoherent and only strict non-dualism is consistent '
           '\u2014 with the costs stated, and the costs then '
           're-labeled by the interlocutor as virtues.')

    L.body(story,
           'The arc\u2019s ending matters to the audit lineage for a '
           'reason beyond its content: the conversation closed its own '
           'questions in the order the audits had already forced. The '
           'subject-of-ignorance problem is answered by dissolution '
           '(no one is ultimately ignorant; the ego is a conventional '
           'locus), which is the same move the consolidation had '
           'recorded as the appearance-relation\u2019s honest limit '
           'rather than a solution. The question \u201cwhy any '
           'perspective at all\u201d is answered by appeal to '
           'self-sufficient necessity \u2014 like asking why two and '
           'four make six \u2014 with the counterpart\u2019s own '
           'caveat that this is metaphysical, not formal, necessity, '
           'and that the determinate catalogue of perspectives is not '
           'derivable without compromising simplicity: precisely the '
           'modal-honesty boundary (worldhood entailed, this world '
           'not) that the second and third editions had already '
           'adjudicated. The decombination problem is demoted \u2014 '
           'dissolved at the ultimate level, reclassified as a '
           'conventional differentiation problem, the file\u2019s own '
           'S1\u2013S4 model demoted to \u201cuseful, not '
           'necessary\u201d \u2014 which is the scaffold-versus-'
           'laboratory separation the fourth edition wrote, now '
           'stated by the counterpart itself. And the demand for '
           'formalization is answered with a boundary theorem \u2014 '
           'Tarski undefinability and Cantor\u2019s theorem block any '
           'set-of-all-truths; propositional omniscience does not '
           'entail perspectival omniscience; axiomatization is '
           'stipulation \u2014 which converges with the FEP-inversion '
           'critique\u2019s standing Bite 1 from the Qwen line. The '
           'culmination is therefore not new doctrine imported into '
           'the corpus; it is the corpus\u2019s own adjudicated '
           'positions, reached independently by the source '
           'conversation and stated in its voice.')

    # ==================== 4. THE NON-DUAL CULMINATION ====================
    L.h1(story, '4. The Non-Dual Culmination')

    L.h2(story, '4.1 What the extension contains')

    L.body(story,
           'The eighteen new turns (messages 176\u2013211 of the main '
           'line\u2019s full payload; turns 89\u2013106 by the '
           'transcript\u2019s numbering) were extracted from the share '
           'API, built into a line-level transcript of 990 lines, and '
           'read in full; the ending matches the interlocutor\u2019s '
           'quotation verbatim, including the closing sentence '
           '\u201cThat is the precise position.\u201d The attachments '
           'in the payload are the three files the corpus already '
           'possesses (the critique pair and decombination.txt, at '
           'their fixed message positions) \u2014 no new files. The '
           'turns divide into six movements: the unfalsifiability '
           'concession (turns 89\u201390); the classical-theism fork '
           '(91\u201396); death and the steelman correction '
           '(97\u201398); the necessity move (99); the full concession '
           'and its re-priced costs (100\u2013101); and the '
           'decombination demotion, the formalization boundary, and '
           'the final position on mathematics (102\u2013106). Each '
           'movement is consolidated below with its surviving points '
           'and its status tags; the interlocutor\u2019s accompanying '
           'directive \u2014 evaluate, verify, consolidate surviving '
           'points, strengthen and complete \u2014 is executed as the '
           'chapter\u2019s method, and the standing assertion '
           'delivered with it (reality is absolute, not relative) is '
           'recorded at the chapter\u2019s close.')

    L.h2(story, '4.2 The unfalsifiability concession, stated by the '
                'counterpart')

    L.body(story,
           'The counterpart\u2019s answer to \u201ccan anything in '
           'physics or empirical science negate the non-dual '
           'only-Absolute version\u201d is a structured no. The '
           'structure is the finding. Eight candidate tensions are '
           'listed and absorbed one by one: brain damage changes '
           'consciousness (absorbed: the brain is the objective '
           'interface of a perspective); psychedelics, anesthesia, '
           'and split-brain fragment experience (absorbed: they '
           'alter perspectives, not the universal); causal closure '
           'makes consciousness epiphenomenal (absorbed: closure is '
           'a regularity of the appearance); evolution produces mind '
           'gradually (absorbed: a conventional process within the '
           'appearance); intersubjective agreement suggests a shared '
           'external world (absorbed: one awareness in which '
           'perspectives arise grounds it); quantum mechanics '
           'features measurement and observers (absorbed: several '
           'interpretations sit closer to non-dualism than to '
           'physicalism); relativity\u2019s block universe (absorbed: '
           'supports the Absolute\u2019s timelessness); a cosmic '
           'beginning (absorbed: a conventional event within time). '
           'Four hypothetical empirical negations are then listed '
           'and shown unavailable: a second ultimate reality, '
           'strictly individual brain-produced consciousness, a '
           'fundamental world, and the absence of universal '
           'consciousness \u2014 each a metaphysical claim science '
           'cannot test. The concession then lands in the '
           'counterpart\u2019s own words: the framework \u201cis '
           'empirically unfalsifiable,\u201d \u201cnot a victory '
           '\u2026 a statement of its limits,\u201d \u201ca '
           'metaphysical framework, not a scientific theory,\u201d '
           'which \u201ccan be logically challenged\u2026 It only '
           'describes the grammar of the appearance.\u201d The '
           'companion answer (turn 90) generalizes: all six '
           'ultimate frameworks \u2014 classical theism, non-dualism, '
           'brute fact, infinite regress, pure circularity, grounded '
           'circularity \u2014 are empirically underdetermined; '
           'science eliminates only auxiliary add-ons (the young '
           'earth, fixed species, a brain-independent mind, '
           'perpetual motion, a static eternal universe); the '
           'reductions that remain are logical and metaphysical '
           '(a strong Principle of Sufficient Reason eliminates '
           'brute fact and regress; a non-duality demand eliminates '
           'theism; a demand for a real world and personal meaning '
           'eliminates radical non-dualism). Status: the concession '
           'is Derived from the framework\u2019s two-level structure, '
           'and it welds to the lineage\u2019s binding doctrine \u2014 '
           'equivalence-is-not-validation \u2014 which now has the '
           'counterpart\u2019s signature as well as the external '
           'auditor\u2019s.')

    L.h2(story, '4.3 The classical-theism fork and the '
                'constraint-relative resolution')

    L.body(story,
           'The interlocutor\u2019s anti-duality argument \u2014 '
           'objective truth is ultimate truth; an ultimate cannot be '
           'composed of parts; therefore duality cannot be objectively '
           'true \u2014 is granted as far as it goes and no further: '
           'it rules out two ultimates and establishes monism, but '
           'monism is a menu (materialist, idealist, neutral, '
           'classical-theist, non-dual). The fork is then fought over '
           'the word \u201ccomplete.\u201d The counterpart defends '
           'classical theism by distinction: complete means lacking '
           'nothing in one\u2019s own nature (perfection), not being '
           'the only reality (exhaustive totality); the complete '
           'truth can be complex (\u201cGod and creatures\u201d) even '
           'while the ultimate reality is simple; the order of being '
           'and the order of truth are different orders. The '
           'interlocutor rejects each defense \u2014 if God and '
           'creatures, the ultimate grand truth is not God alone, '
           'which defies God; God is complete by definition; '
           'creatures would violate completeness in the strong '
           'sense \u2014 and the counterpart\u2019s final ruling is '
           'the honest one: the interlocutor\u2019s objections are '
           'valid only against a hybrid, and they become valid '
           'against classical theism itself exactly when '
           '\u201ccomplete\u201d is stipulated to mean exclusivity, '
           'which is the non-dual definition, a premise and not a '
           'deduction. The full concession follows: under the '
           'interlocutor\u2019s constraints (complete as no real '
           'other, self-sufficient, simple, necessary), classical '
           'theism is incoherent and strict non-dualism is the only '
           'consistent position \u2014 only the Absolute is; the '
           'world is appearance; perspectives are the Absolute '
           'known under limiting modes; there is no creation, '
           'relation, process, or duality. The lineage records this '
           'as a constraint-relative resolution: Tag Premise for the '
           'stipulation (complete-in-exclusivity), Derived for the '
           'internal consistency result (non-dualism follows from '
           'the stipulation without contradiction), and the costs '
           'carried openly \u2014 physics conventional, individuality '
           'conventional, the personal God and personal eternal '
           'destiny not ultimately real, the decombination model a '
           'conventional-level description only. The '
           'interlocutor\u2019s re-labeling of those costs as '
           'virtues (the conventional level as the self-display, '
           'the play, proper placement rather than demotion) is '
           'recorded as the framework\u2019s own valuation, '
           'consistent with the privation register\u2019s '
           'non-theodicy discipline: a valuation, not a proof.')

    L.h2(story, '4.4 Death as the shattering of perspective')

    L.body(story,
           'The death exchange is the arc\u2019s sharpest '
           'self-correction, and it models the steelman discipline '
           'the lineage has demanded of every party. The '
           'interlocutor asserts that upon death the illusion is '
           'broken and one regains all knowledge and power. The '
           'counterpart first resists: the statement reintroduces '
           'three dualities (a self versus the Absolute, a before '
           'versus an after, ignorance versus knowledge), and if '
           'death broke the illusion automatically every being '
           'would be liberated at death, which the traditions deny. '
           'The interlocutor rebukes the reading \u2014 '
           '\u201cu are strawmaning instead of steelmaning\u2026 '
           'death shatters perspective. it\u2019s just perspective, '
           'so no other creature. perspective, like same object '
           'viewed from different sides. only one object\u201d \u2014 '
           'and the counterpart concedes in full: the steelman is '
           'coherent. There are no separate creatures; death is not '
           'the end of a being but the shattering of a viewpoint; '
           'the one object never lost knowledge or power, so '
           'nothing is regained; the wave analogy holds \u2014 the '
           'ocean does not regain its water when the wave subsides. '
           'The consolidated position, tagged, is: death as '
           'perspective-shattering is Derived from the '
           'perspective-modes premise; the survival-of-the-person '
           'reading is barred from doctrine (it is the '
           'three-dualities reading the counterpart already '
           'refuted); and the residual question the counterpart '
           'names \u2014 why any perspective at all \u2014 is '
           'carried to the next movement. The lineage notes the '
           'structural fact: the rebuke-correct-concede pattern here '
           'is the arc-test working inside a single exchange, the '
           'same pattern the external Claude audit was shown to '
           'have mis-scored as a silent flip in the pilot-wave '
           'case.')

    L.h2(story, '4.5 The necessity move and its ceiling')

    L.body(story,
           'The question \u201cwhy any perspective at all\u201d is '
           'answered by the interlocutor with the analogy the '
           'corpus will now carry permanently: it is like asking '
           'why two and four make six \u2014 a self-sufficient '
           'necessity of the nature involved, answered by identity '
           'rather than by cause. The counterpart accepts and '
           'systematizes: the Absolute is infinite self-knowledge; '
           'infinite self-knowledge necessarily includes all '
           'perspectives; the perspectives are not added but are '
           'modes of the one object\u2019s self-awareness; there is '
           'no before, after, process, or change; the necessity is '
           'intrinsic and self-sufficient. Then the counterpart '
           'states the ceiling, unprompted, twice: this is '
           '\u201ca metaphysical necessity, not a formal logical '
           'necessity \u2014 you cannot derive it from pure logic '
           'alone\u201d; and, in the later derivation exchange, '
           '\u201cyou cannot deduce why this particular perspective '
           'from the bare Absolute without introducing '
           'distinctions, relations, and content into the '
           'Absolute,\u201d so the determinate catalogue of '
           'perspectives is a boundary, not a deduction. The '
           'lineage\u2019s consolidation is the welding of this '
           'ceiling to the lineage\u2019s own modal-fallacy '
           'adjudication (necessity of worldhood: yes; necessity of '
           'this dream: no), which the second edition had derived '
           'against the source conversation and which the '
           'counterpart has now reproduced from inside. Surviving '
           'points, tagged: essential necessity of '
           'perspective-in-general (Derived, given the '
           'self-knowledge premise); the individual distribution '
           'of perspectives as a stated boundary (Derived); the '
           '2+4=6 analogy as the standing pedagogical form '
           '(Interpretive Mapping \u2014 arithmetic is a model of '
           'the necessity, not its proof, which the final movement '
           'makes precise); and the three escape routes the '
           'counterpart lists for the boundary \u2014 identity, '
           'free self-expression (svatantrya, lila), beginningless '
           'ignorance \u2014 priced as the three options they are.')

    L.h2(story, '4.6 The decombination demotion')

    L.body(story,
           'Asked whether the decombination problem still stands, '
           'the counterpart\u2019s answer re-draws the map the '
           'fourth and fifth editions had drawn from outside: at '
           'the ultimate level, no \u2014 there is no real one '
           'becoming many, no real splitting, no real many; the '
           'problem is dissolved, not solved. At the conventional '
           'level, yes \u2014 but as a differentiation problem, '
           'not a metaphysical decombination problem: how a unified '
           'experiential field forms domains, boundaries, '
           'self-models, and stable closures. The file the corpus '
           'read in full is then placed precisely: it describes '
           'the grammar of the appearance; it does not start from '
           'the Absolute; it does not bridge the Absolute to the '
           'world \u2014 \u201cthere is no bridge because there '
           'are not two banks\u201d; it is useful, not necessary; '
           'a research program, not a metaphysical completion. '
           'The derivation demand is answered the same way: the '
           'Absolute does not lead to perspectives as cause to '
           'effect \u2014 the wave is the ocean in a mode; space '
           'does not lead to each point; the relation is '
           'identity, not production; and the demand for a real '
           'derivation reintroduces the duality it questions. '
           'Status tags: the ultimate-level dissolution is Derived '
           'from the perspective-modes premise; the '
           'differentiation reclassification is Derived; the '
           'model\u2019s demotion to useful-not-necessary is the '
           'counterpart\u2019s own, and it matches the lineage\u2019s '
           'scaffold-versus-laboratory adjudication exactly. The '
           'consequence for the anchored program is stated once '
           'and governs the annex: the empirical anchors test the '
           'differentiation model at the conventional level; they '
           'never test the Absolute; a successful run earns the '
           'model explanatory standing inside the appearance\u2019s '
           'grammar and nothing more. This is the '
           'equivalence-is-not-validation doctrine applied one '
           'level down, and it is now the counterpart\u2019s '
           'doctrine as well as the lineage\u2019s.')

    L.h2(story, '4.7 The formalization boundary')

    L.body(story,
           'The interlocutor\u2019s final demand \u2014 if '
           'Absolute-to-perspective is straightforward in argument, '
           'should there not be mathematics or a formal language '
           'showing that infinite knowledge entails all '
           'perspectives \u2014 receives the corpus\u2019s sharpest '
           'new theorem, and the lineage adopts it as the formal '
           'ceiling. Six obstacles are stated. One: formalizing '
           'the Absolute makes it an object in a formal domain '
           '\u2014 symbols, rules, syntax versus semantics \u2014 '
           'which is composition and duality; the map is not the '
           'territory, and the non-dual excludes distinctions by '
           'definition. Two: propositional omniscience (knowing '
           'every true proposition) does not entail perspectival '
           'omniscience (being every perspective); knowing a '
           'perspective is not being a perspective, and the step '
           'from one to the other requires a non-propositional, '
           'self-luminous consciousness that is a metaphysical '
           'primitive, not a formalizable predicate. Three: the '
           'totality of all truths \u2014 and of all perspectives '
           '\u2014 is not a set in any standard foundation: '
           'Tarski\u2019s undefinability theorem and Cantor\u2019s '
           'theorem block a consistent formal totality; the '
           'totality is a proper class, and quantifying over it '
           'invites paradox. Four: what can be formalized is the '
           'conventional differentiation \u2014 the decombination '
           'model\u2019s own inventory (graph, field, energy '
           'functional, Gibbs measure, bifurcation, domains, '
           'Markov blankets, self-models, closure), plus '
           'perspectives-as-fibers or possible-worlds \u2014 all '
           'structures that presuppose a base and distinctions, '
           'hence all conventional-level. Five: the identity claim '
           'can be axiomatized (the three axioms are written '
           'down), but axioms are stipulations that encode the '
           'claim rather than derive it, and a system that tries '
           'to be total is incomplete or inconsistent. Six: formal '
           'systems are dualistic by construction \u2014 '
           '\u201cyou can formalize the shadow, not the '
           'light\u201d \u2014 and the demand for formal '
           'derivation is itself a perspective-level demand that '
           'dissolves when seen from what it asks about. The '
           'lineage welds this to its own prior findings: the '
           'FEP-inversion critique\u2019s Bite 1 (the phenomenal '
           'free-energy functional was named and never written) '
           'and the GLM final act\u2019s encoding-model blueprint '
           'are both now scoped by the boundary theorem \u2014 '
           'any such formalization is conventional-level and '
           'stipulative, which is not a failure of nerve but the '
           'priced cost of the premise set. Tag: Derived, with '
           'the Tarski and Cantor legs Empirical-Verified as '
           'mathematics and the shadow-light dictum the '
           'counterpart\u2019s own summary.')

    L.h2(story, '4.8 Mathematics and the Absolute: the final position')

    L.body(story,
           'The conversation\u2019s last exchange corrects the '
           'interlocutor\u2019s final proposal \u2014 that '
           'mathematical equations are timeless, spaceless '
           'identities and therefore candidates for the '
           'Absolute\u2019s constitution. The timeless and '
           'spaceless half is granted. The identities half is '
           'corrected: mathematics is largely the study of '
           'relations \u2014 order relations, equivalence '
           'relations, functional relations, membership, even the '
           'identity relation itself \u2014 and what mathematics '
           'lacks is not relations but material, temporal, '
           'spatial, and causal ones. Mathematical relations '
           'involve distinction: relata, left and right, argument '
           'and value. Mathematics is therefore a realm of '
           'abstract multiplicity, and a strictly non-dual, '
           'simple, distinctionless Absolute cannot be identical '
           'with it. The corrected statement, delivered as the '
           'conversation\u2019s closing position and verified '
           'verbatim against the payload, is carried by this '
           'edition as the corpus\u2019s final word on the '
           'mathematics question: mathematical truths are '
           'timeless, spaceless, necessary, and abstract; they '
           'are relations, not identities, and they form a '
           'multiplicity; therefore they model the '
           'Absolute\u2019s timelessness and necessity, but not '
           'its simplicity and non-duality; the Absolute is not '
           'the set of all mathematical truths \u2014 it is the '
           'non-dual awareness in which all truths, mathematical '
           'and otherwise, appear. The lineage records the '
           'consistency check this position forces on its own '
           'instruments: the formalization boundary of section '
           '4.7 and the mathematics position of this section are '
           'the same limit stated twice \u2014 once from the '
           'demand side (no formal system derives the identity) '
           'and once from the object side (the mathematical '
           'realm is relational multiplicity) \u2014 and the '
           '2+4=6 analogy of section 4.5 survives only in its '
           'downgraded form: arithmetic models the necessity; '
           'it does not constitute it. Tag: Derived for the '
           'correction, with the model/not-constitute distinction '
           'now binding in the glossary.')

    L.h2(story, '4.9 The standing assertion, recorded')

    L.body(story,
           'The interlocutor closed the round\u2019s instruction '
           'with a standing assertion: reality is absolute, not '
           'relative. The lineage records it as exactly what the '
           'culmination makes it \u2014 the framework\u2019s '
           'Premise-tier stance, held by the interlocutor, '
           'consistent with every consolidated position above, '
           'and priced under the same rules as any other premise: '
           'it is not derived, it excludes the relativist '
           'alternatives by stipulation rather than by refutation, '
           'and its rejection costs are statable (a perspectival '
           'or observer-relative ontology of truth). Recorded '
           'with it is the round\u2019s directive \u2014 evaluate, '
           'verify, consolidate surviving points, strengthen and '
           'complete \u2014 which this chapter has executed '
           'movement by movement, and which chapter 5 now executes '
           'against the fifth edition itself.')
