#!/usr/bin/env python3
"""Seventh Edition (Parameter-Map Edition), Part 2: chapter 3 \u2014 the
five newly-read sources, one section each, with what each contributes to
the parameter map."""
import fhcp_pdf_lib as L


def add_content(story):
    # ==================== 3. FIVE NEW SOURCES ====================
    L.h1(story, '3. The Five New Sources, Read from Source')

    L.body(story,
           'The interlocutor supplied five papers in response to the '
           'round-seventeen fetch record. Four were precisely the '
           'load-bearing items the environment could not fetch; the fifth '
           'was new to the corpus. All five have been read line by line '
           'from the supplied PDFs (the extractions are archived in the '
           'research directory with page markers intact). One filing '
           'correction is recorded for provenance: the file uploaded under '
           'the name of this project\u2019s own Survival Test PDF contained '
           'the Deco et al. 2018 Current Biology paper \u2014 the '
           'publisher-blocked psychedelic parameterization study \u2014 '
           'which is how the Cell Press full text entered the corpus; the '
           'project\u2019s own Survival Test PDF remains intact and '
           'unaffected in the deliverables directory. This chapter '
           'summarizes what each source actually says and what each '
           'contributes to the map; the protocol of chapter 5 then uses '
           'them as named methods. Throughout, the citation tags P1\u2013P5 '
           'refer to these five papers in the order introduced here.')

    L.h2(story, '3.1 P1 \u2014 The Virtual Epileptic Patient (Jirsa et al. 2017, NeuroImage)')

    L.body(story,
           'The Virtual Epileptic Patient (VEP) demonstrates, on a fully '
           'worked clinical case, that a patient-specific spatial parameter '
           'map can be inferred from intracranial recordings by Bayesian '
           'inversion of a whole-brain network model. The node model is '
           'the Epileptor, a five-variable neural mass acting on three '
           'time scales; the load-bearing parameter is the excitability '
           'x<sub>0</sub>, which controls whether a region can trigger '
           'seizures autonomously, with a critical value '
           'x<sub>0C</sub> = \u22122.05 separating healthy from '
           'epileptogenic tissue. Nodes couple through the slow '
           'permittivity variable with strength K<sub>ij</sub> = '
           'G\u00b7C<sub>ij</sub> \u2014 a global scalar times the '
           'individual diffusion-MRI connectome \u2014 and the patient\u2019s '
           'MRI lesion (a hypothalamic hamartoma) enters as a local '
           'coupling scalar G<sub>hyp</sub> applied to the lesioned '
           'region\u2019s connections. The excitability map is thus the '
           'direct analogue, in this foreign literature, of the '
           'specification\u2019s spatial phase field: a heterogeneous '
           'regional parameter over a real connectome whose distribution '
           'determines which domains become unstable.')

    L.body(story,
           'Two methodological results matter for the map. First, the '
           'inversion: the model is fit to stereo-EEG data by extracting '
           'high-frequency power above 10 Hz, log-transforming and '
           'detrending it, and treating the fast-discharge variable as the '
           'latent state of an observation model whose noise is Gaussian; '
           'inference over per-node excitability uses Hamiltonian Monte '
           'Carlo and variational inference in Stan, and recovers a '
           'posterior density \u2014 a violin plot \u2014 for every '
           'region, not merely a point estimate. The inversion correctly '
           'reconstructs the observed seizure propagation between areas and '
           'identifies the bilateral mesial temporal epileptogenic zone, '
           'in agreement with the clinical reading; a companion '
           'fifteen-patient study (Proix and colleagues) confirmed that '
           'VEP-predicted zones correlate with expert stereo-EEG opinion '
           'and that individual connectomes improve the prediction '
           'significantly. Second, the parameter-space navigation charts: '
           'systematic exploration over (G, G<sub>hyp</sub>, '
           'x<sub>0</sub> of the right hippocampus, x<sub>0</sub> of '
           'unrecruited regions) yields contour maps of seizure frequency '
           'per region that behave non-trivially and non-monotonically '
           '\u2014 increasing global coupling G, for this patient, was the '
           'only route to more thalamic seizures, while lowering '
           'hypothalamic coupling always increased hypothalamic seizures. '
           'The paper\u2019s own discussion states the honest limit that '
           'the map inherits: the correspondence between model parameters '
           'and physiological parameters is non-bijective \u2014 one '
           'x<sub>0</sub> reflects excitation\u2013inhibition balance, '
           'synaptic efficacy, ionic homeostasis, and glial activity '
           'together \u2014 which poses an identification challenge for '
           'the clinic and, for this corpus, a standing caution against '
           'over-reading any single parameter\u2019s neural meaning.')

    L.h2(story, '3.2 P2 \u2014 Hierarchical Critical Synchronization (Myrov et al., bioRxiv)')

    L.body(story,
           'The Myrov study supplies the missing middle of the '
           'criticality arm: a whole-brain model whose control parameters '
           'are exactly coupling strengths, whose critical regime is '
           'defined by a published operational criterion, and whose '
           'operating point is estimated per subject against '
           'magnetoencephalography. The model is hierarchical Kuramoto: '
           'each cortical parcel is a node containing a population of '
           'coupled phase oscillators, so that local (within-node) '
           'synchronization and global (between-node) synchronization are '
           'separable. Each oscillator\u2019s phase advances under a '
           'natural-frequency term, an internal coupling term scaled by '
           'the local parameter K, an external term that couples the '
           'oscillator to other nodes\u2019 average phases with strength '
           'L\u00b7W<sub>nj</sub> weighted by node order '
           'R<sub>j</sub> \u2014 W being the structural connectome '
           'weight \u2014 and white noise. The two control parameters, K '
           'and L, span a plane; on that plane the study maps node order, '
           'the detrended-fluctuation-analysis exponent, phase-locking '
           'values, and amplitude cross-correlations.')

    L.body(story,
           'The critical regime is defined operationally and conservatively: '
           'the region of the (K, L) plane in which more than ten percent '
           'of nodes exhibit DFA exponents above 0.65, a threshold set '
           'against the ninety-fifth percentile of exponent values from '
           'white-noise surrogates. The critical region forms a ridge on '
           'the K\u2013L surface; long-range temporal correlations peak '
           'there; inter-subject variance across the twenty-four '
           'individual-connectome models is maximal there; and '
           'structure\u2013function coupling \u2014 the correlation between '
           'structural measures and dynamical observables \u2014 peaks at '
           'criticality for the DFA exponent and for amplitude '
           'cross-correlations while dipping for phase synchronization. '
           'Null models with shuffled or randomized connectomes produce '
           'non-significant model\u2013MEG correspondence, establishing '
           'that the realistic topology, not mere oscillator dynamics, '
           'carries the match. The decisive result for the map: when model '
           'observables are compared parcel by parcel and edge by edge '
           'against individual-subject MEG, the significant correlations '
           'lie along the critical ridge, and the best overall match sits '
           'on the subcritical side of the extended critical regime '
           '\u2014 the human brain, in this framework, runs near but not '
           'at the transition. The study even samples each node\u2019s '
           'oscillator frequency distribution from the subject\u2019s '
           'measured power spectrum (with the aperiodic component removed), '
           'preserving the multi-peak spectrum; spectral matching is again '
           'best near criticality. For the corpus, this is the published '
           'estimator of distance-to-criticality on real connectomes: the '
           'quantity the specification\u2019s J-versus-J<sub>c</sub> '
           'structure needs, instantiated per subject.')

    L.h2(story, '3.3 P3 \u2014 Serotonin Receptor Maps Explain LSD (Deco et al. 2018, Current Biology)')

    L.body(story,
           'The Deco study is the psychedelic arm\u2019s parameter map in '
           'already-published form, and its architecture is startlingly '
           'economical. A dynamic mean-field model of ninety '
           'AAL-parcellated regions \u2014 each node a mean-field of '
           'integrate-and-fire populations, eighty percent excitatory and '
           'twenty percent inhibitory \u2014 is coupled by the '
           'tractography connectome and carries exactly two parameters: '
           'the global coupling G (one scalar for all fibers) and the '
           'neuromodulator gain-scaling s<sub>E</sub>. The regional '
           'excitatory gains are modulated by s<sub>E</sub> weighted by '
           'the empirical regional density of the 5-HT2A receptor, taken '
           'from a high-resolution in-vivo PET atlas built with the '
           'selective agonist radioligand [<super>11</super>C]Cimbi-36 in '
           '210 healthy subjects. The fitting target is the functional '
           'connectivity dynamics \u2014 the distribution of '
           'sliding-window functional-connectivity values, compared by '
           'Kolmogorov\u2013Smirnov distance \u2014 which is more '
           'constraining than static connectivity. The procedure: fit G '
           'to the placebo condition with unmodulated gains (optimum '
           'G = 2.1), freeze it, and ask whether any single '
           's<sub>E</sub> reproduces the LSD condition.')

    L.body(story,
           'It does: an optimal s<sub>E</sub> of approximately 0.2, with '
           'the receptor-density map doing all the spatial work, explains '
           'the non-linear functional effects of a 75-microgram intravenous '
           'dose. The controls are the part that makes this a parameter '
           'map rather than a fit. Shuffling the ninety receptor-density '
           'values across regions (two hundred random permutations) '
           'significantly degrades the explanation; a uniform map is the '
           'worst of all; and substituting the density maps of other '
           'serotonin targets \u2014 5-HT1A, 5-HT1B, 5-HT4, and the '
           'transporter \u2014 performs significantly worse, with 5-HT1A '
           'the best of the wrong receptors, matching its known '
           'contributory role. Training and testing on disjoint random '
           'halves of participants generalizes. The open code (the '
           'decolab repository) and the open receptor atlas make the '
           'entire pipeline reproducible. For the map: receptor density '
           'is the published bridge from molecular pharmacology to a '
           'regional model parameter, and the drug state is carried by one '
           'scalar \u2014 exactly the structure requirement 4 asks the '
           'psychedelic arm to have.')

    L.h2(story, '3.4 P4 \u2014 Ketanserin Blockade Attributes LSD to 5-HT2A (Preller et al. 2018, eLife)')

    L.body(story,
           'The Preller study supplies what no modeling paper can: the '
           'intervention. In a double-blind, randomized, counterbalanced, '
           'cross-over design, twenty-four healthy participants received '
           'placebo plus placebo, placebo plus LSD (100 micrograms oral), '
           'or ketanserin \u2014 a selective 5-HT2A antagonist \u2014 '
           'plus LSD. The analysis uses global brain connectivity: each '
           'voxel\u2019s average correlation with every other voxel, '
           'computed with global-signal regression and protected by '
           'threshold-free cluster enhancement over ten thousand '
           'permutations. LSD produced hyper-connectivity in sensory and '
           'somatomotor cortex \u2014 occipital cortex, superior temporal '
           'gyrus, postcentral gyrus, precuneus \u2014 and in the '
           'thalamus, with simultaneous hypo-connectivity across '
           'associative networks \u2014 medial and lateral prefrontal '
           'cortex, cingulum, insula, temporoparietal junction \u2014 and '
           'subcortical structures. Ketanserin abolished the entire '
           'pattern: the drug-condition maps for LSD versus placebo and '
           'LSD versus ketanserin-plus-LSD correlate at r = 0.91, the '
           'contrast of ketanserin-plus-LSD against placebo is '
           'negligible, and every subjective scale of the 5D-ASC '
           'questionnaire that LSD elevated is returned to placebo '
           'levels by the blocker (all comparisons between placebo and '
           'ketanserin-plus-LSD non-significant).')

    L.body(story,
           'Two further results tighten the attribution. Across '
           'participants, the strength of sensory hyper-connectivity and '
           'associative hypo-connectivity are strongly anti-correlated '
           '(r = \u22120.90), indicating a single systems-level '
           'perturbation rather than two independent effects \u2014 '
           'exactly the structure a bifurcation account predicts, where '
           'one control parameter\u2019s crossing redistributes '
           'integration rather than adding and subtracting connections '
           'independently. And the spatial pattern of LSD-induced '
           'connectivity change matches the cortical gene-expression '
           'profile of the 5-HT2A receptor (HTR2A) from the Allen Human '
           'Brain Atlas, preferentially over other receptors. For the '
           'map\u2019s epistemic grade, this is the difference between '
           'correlation and intervention: the psychedelic arm\u2019s key '
           'variable is not merely associated with the observed dynamics '
           'but causally necessary for them, blocked and restored by '
           'pharmacology in humans. The corpus\u2019s own standard \u2014 '
           'S3-type evidence must not survive destruction of the '
           'mechanism it claims to model \u2014 is met by the '
           'counterpart experiment at the pharmacological level.')

    L.h2(story, '3.5 P5 \u2014 Metabolic Connectivity Mapping (Riedl et al., PNAS)')

    L.body(story,
           'The fifth paper contributes a different quantity: direction. '
           'Metabolic connectivity mapping (MCM) integrates undirected '
           'functional connectivity from fMRI with regional energy '
           'metabolism from FDG-PET acquired simultaneously in the same '
           'scanner session, exploiting the biophysical fact that the '
           'majority of signaling-related energy \u2014 up to '
           'seventy-five percent \u2014 is consumed postsynaptically, at '
           'the target of a signal rather than its source. For each '
           'functional pathway between regions, the spatial correlation '
           'between voxel-wise functional connectivity to the source and '
           'voxel-wise glucose uptake in the candidate target identifies '
           'which side carries the metabolic load, and hence the '
           'direction of afferent signaling. The analysis is performed on '
           'unsmoothed, non-normalized data so that it works per subject, '
           'voxel by voxel, across the whole cortex. Validation uses the '
           'one sensory modality that can be volitionally interrupted: '
           'comparing eyes-closed with eyes-open rest, MCM recovers '
           'stable bidirectional communication among early and higher '
           'visual areas in both conditions, stable top-down signaling '
           'from a frontoparietal network, and \u2014 only in the '
           'eyes-open condition \u2014 additional top-down signaling from '
           'salience-network regions onto early visual cortex, a '
           'hierarchy consistent with the tracer literature.')

    L.body(story,
           'For the map, MCM supplies two things the other four papers '
           'do not. First, a directional observable: the '
           'specification\u2019s coupling is symmetric in its '
           'Ginzburg\u2013Landau form, but any neural realization must '
           'choose directed effective connectivity, and MCM is a '
           'published, per-subject, whole-brain method for asymmetrizing '
           'the coupling matrix from energy rather than from '
           'hemodynamic lags. Second, an energy observable: the '
           'free-energy functional of the specification is an abstract '
           'quantity, and FDG uptake is its closest published physiological '
           'shadow \u2014 a fact the protocol can use to give the '
           'g and a parameters an energetic reading at the regional '
           'level. The method\u2019s limits are equally instructive: it '
           'requires simultaneous PET\u2013MRI acquisition, which '
           'constrains the datasets it can serve, and it inherits '
           'PET\u2019s minutes-scale temporal resolution, so it '
           'constrains direction, not dynamics. The protocol therefore '
           'uses MCM as a prior on coupling asymmetry where simultaneous '
           'acquisitions exist, and as the energy-side cross-check on '
           'parameter maps elsewhere.')

    L.callout(story,
              'What the five sources jointly establish',
              'A spatial excitability parameter can be inferred per '
              'patient from intracranial recordings by Bayesian '
              'inversion (P1). A per-subject distance to the critical '
              'coupling regime can be estimated against '
              'magnetoencephalography (P2). A molecular receptor map '
              'can carry a drug state into regional model parameters '
              'through a single scalar, with shuffled-map and '
              'wrong-receptor controls (P3). The key variable of the '
              'psychedelic arm is intervention-validated in humans '
              '(P4). Direction and energy observables exist at '
              'whole-brain, per-subject resolution (P5). None of these '
              'is the neural parameter map of requirement 4 \u2014 but '
              'every one of its six parameters now has at least one '
              'published estimation route, which was not true of any '
              'of them when the requirement was written.')
