#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Build the body PDF for 'The Dream That Must Be — Trilogy Edition' (v2, Report route).
Cover is built separately (Template 03 via html2poster.js) and merged afterwards.
"""
import os, re, sys, hashlib

SKILL = '/home/z/my-project/skills/pdf'
BASE = '/home/z/my-project'
sys.path.insert(0, os.path.join(SKILL, 'scripts'))
sys.path.insert(0, os.path.join(BASE, 'scripts'))

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.enums import TA_JUSTIFY, TA_LEFT, TA_CENTER
from reportlab.lib.styles import ParagraphStyle
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, PageBreak,
                                Table, TableStyle, KeepTogether, CondPageBreak,
                                HRFlowable)
from reportlab.platypus.tableofcontents import TableOfContents

import critique_content_v2 as C

# ── Fonts (allowed set only) ─────────────────────────────────────────────
FONT_DIR = '/usr/share/fonts'

def _reg(name, path):
    full = os.path.join(FONT_DIR, path)
    if not os.path.exists(full):
        raise SystemExit('missing font: %s' % full)
    pdfmetrics.registerFont(TTFont(name, full))

_reg('NotoSerifSC',      'truetype/noto-serif-sc/NotoSerifSC-Regular.ttf')
_reg('NotoSerifSC-Bold', 'truetype/noto-serif-sc/NotoSerifSC-Bold.ttf')
if os.path.exists(os.path.join(FONT_DIR, 'truetype/chinese/NotoSansSC-Regular.ttf')):
    _reg('Noto Sans SC',      'truetype/chinese/NotoSansSC-Regular.ttf')
    _reg('Noto Sans SC Bold', 'truetype/chinese/NotoSansSC-Bold.ttf')
if os.path.exists(os.path.join(FONT_DIR, 'truetype/chinese/SarasaMonoSC-Regular.ttf')):
    _reg('SarasaMonoSC', 'truetype/chinese/SarasaMonoSC-Regular.ttf')
_reg('FreeSerif',           'truetype/freefont/FreeSerif.ttf')
_reg('FreeSerif-Bold',      'truetype/freefont/FreeSerifBold.ttf')
_reg('FreeSerif-Italic',    'truetype/freefont/FreeSerifItalic.ttf')
_reg('FreeSerif-BoldItalic','truetype/freefont/FreeSerifBoldItalic.ttf')
_reg('DejaVuSans',          'truetype/dejavu/DejaVuSansMono.ttf')

registerFontFamily('NotoSerifSC', normal='NotoSerifSC', bold='NotoSerifSC-Bold')
registerFontFamily('Noto Sans SC', normal='Noto Sans SC', bold='Noto Sans SC Bold')
registerFontFamily('FreeSerif', normal='FreeSerif', bold='FreeSerif-Bold',
                   italic='FreeSerif-Italic', boldItalic='FreeSerif-BoldItalic')
registerFontFamily('DejaVuSans', normal='DejaVuSans', bold='DejaVuSans')

from pdf import install_font_fallback
install_font_fallback()

# ━━ Cascade Palette (auto-generated by design_engine.py palette-cascade) ━━
PAGE_BG       = colors.HexColor('#f5f5f4')
SECTION_BG    = colors.HexColor('#f2f1f0')
CARD_BG       = colors.HexColor('#ebeae8')
TABLE_STRIPE  = colors.HexColor('#ededeb')
HEADER_FILL   = colors.HexColor('#4e4732')
COVER_BLOCK   = colors.HexColor('#746c56')
BORDER        = colors.HexColor('#c5bfac')
ICON          = colors.HexColor('#a48e4b')
ACCENT        = colors.HexColor('#92761f')
ACCENT_2      = colors.HexColor('#3aa0c2')
TEXT_PRIMARY  = colors.HexColor('#151513')
TEXT_MUTED    = colors.HexColor('#7e7c74')
TABLE_HEADER_COLOR = HEADER_FILL
TABLE_HEADER_TEXT  = colors.white
TABLE_ROW_EVEN     = colors.white
TABLE_ROW_ODD      = TABLE_STRIPE

# ── Geometry ─────────────────────────────────────────────────────────────
MARGIN   = 1.0 * inch
PAGE_W, PAGE_H = A4
AVAIL_W  = PAGE_W - 2 * MARGIN
AVAIL_H  = PAGE_H - 2 * MARGIN
MAX_KEEP_HEIGHT = PAGE_H * 0.4

OUT_BODY = os.path.join(BASE, 'scripts', '_body_v2.pdf')

# ── Markup: **bold**, *italic* → ReportLab tags ─────────────────────────
def esc(t):
    # NOTE: entities are built by concatenation so code.sanitize's
    # html.unescape pass cannot decode them back into raw characters.
    AMP = '&' + 'amp;'
    LT  = '&' + 'lt;'
    GT  = '&' + 'gt;'
    return t.replace('&', AMP).replace('<', LT).replace('>', GT)

def md(t):
    t = esc(t)
    t = re.sub(r'\*\*(.+?)\*\*', r'<b>\1</b>', t, flags=re.S)
    t = re.sub(r'\*(.+?)\*', r'<i>\1</i>', t, flags=re.S)
    # Bind em-dashes to the preceding word (prevents line-start dash)
    t = t.replace(' \u2014 ', '\u00a0\u2014 ')
    return t

# ── Styles ───────────────────────────────────────────────────────────────
BODY = ParagraphStyle('Body', fontName='FreeSerif', fontSize=10.5, leading=17,
                      alignment=TA_JUSTIFY, spaceBefore=0, spaceAfter=10,
                      textColor=TEXT_PRIMARY)
H1 = ParagraphStyle('H1', fontName='FreeSerif-Bold', fontSize=22, leading=27,
                    textColor=TEXT_PRIMARY, spaceBefore=16, spaceAfter=4)
H2 = ParagraphStyle('H2', fontName='FreeSerif-Bold', fontSize=15, leading=20,
                    textColor=HEADER_FILL, spaceBefore=14, spaceAfter=6)
QUOTE = ParagraphStyle('Quote', fontName='FreeSerif-Italic', fontSize=10.5,
                       leading=16.5, alignment=TA_LEFT, textColor=TEXT_PRIMARY)
CAPTION = ParagraphStyle('Caption', fontName='FreeSerif', fontSize=8.5, leading=12,
                         alignment=TA_CENTER, textColor=TEXT_MUTED,
                         spaceBefore=4, spaceAfter=6)
NOTE = ParagraphStyle('Note', fontName='FreeSerif-Italic', fontSize=9, leading=13.5,
                      alignment=TA_LEFT, textColor=TEXT_MUTED, spaceAfter=12)
TH = ParagraphStyle('TH', fontName='FreeSerif', fontSize=9.5, leading=13,
                    textColor=TABLE_HEADER_TEXT, alignment=TA_LEFT)
TC = ParagraphStyle('TC', fontName='FreeSerif', fontSize=9, leading=12.5,
                    textColor=TEXT_PRIMARY, alignment=TA_LEFT)
TOC_TITLE = ParagraphStyle('TOCTitle', fontName='FreeSerif-Bold', fontSize=20,
                           leading=25, textColor=TEXT_PRIMARY, spaceAfter=14)
TOC_L0 = ParagraphStyle('TOCL0', fontName='FreeSerif', fontSize=11.5, leading=20,
                        textColor=TEXT_PRIMARY, leftIndent=6)
TOC_L1 = ParagraphStyle('TOCL1', fontName='FreeSerif', fontSize=10, leading=17,
                        textColor=TEXT_MUTED, leftIndent=26)

# ── Doc template with TOC support ────────────────────────────────────────
class TocDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, 'bookmark_name'):
            level = getattr(flowable, 'bookmark_level', 0)
            text = getattr(flowable, 'bookmark_text', '')
            key = getattr(flowable, 'bookmark_key', '')
            self.notify('TOCEntry', (level, text, self.page, key))

def add_heading(text, style, level=0):
    key = 'h_' + hashlib.md5((str(level) + text).encode()).hexdigest()[:8]
    p = Paragraph('<a name="%s"/><b>%s</b>' % (key, md(text)), style)
    p.bookmark_name = key
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    return p

def safe_keep_together(elements):
    total_h = 0
    for el in elements:
        w, h = el.wrap(AVAIL_W, PAGE_H)
        total_h += h
    if total_h <= MAX_KEEP_HEIGHT:
        return [KeepTogether(elements)]
    elif len(elements) >= 2:
        return [KeepTogether(elements[:2])] + list(elements[2:])
    return list(elements)

def quote_block(text):
    inner = Paragraph(md(text), QUOTE)
    t = Table([[inner]], colWidths=[AVAIL_W * 0.92], hAlign='CENTER')
    t.setStyle(TableStyle([
        ('LINEBEFORE', (0, 0), (0, -1), 2, ACCENT),
        ('BACKGROUND', (0, 0), (-1, -1), SECTION_BG),
        ('LEFTPADDING', (0, 0), (-1, -1), 14),
        ('RIGHTPADDING', (0, 0), (-1, -1), 10),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
    ]))
    return [Spacer(1, 6)] + safe_keep_together([t]) + [Spacer(1, 10)]

def data_table(spec):
    ratios = spec['ratios']
    assert abs(sum(ratios) - 1.0) < 1e-6, 'ratios must sum to 1.0'
    col_widths = [r * AVAIL_W for r in ratios]
    assert sum(col_widths) <= AVAIL_W + 0.5
    header = [Paragraph('<b>%s</b>' % md(h), TH) for h in spec['header']]
    rows = [header]
    for r in spec['rows']:
        rows.append([Paragraph(md(cell), TC) for cell in r])
    t = Table(rows, colWidths=col_widths, hAlign='CENTER', repeatRows=1)
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [TABLE_ROW_EVEN, TABLE_ROW_ODD]),
        ('GRID', (0, 0), (-1, -1), 0.5, BORDER),
        ('VALIGN', (0, 0), (-1, 0), 'MIDDLE'),
        ('VALIGN', (0, 1), (-1, -1), 'TOP'),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
    ]))
    cap = Paragraph(md(spec['caption']), CAPTION)
    out = [Spacer(1, 12)]
    if len(spec['rows']) <= 5:
        out += safe_keep_together([t, cap])
    else:
        out += [t, cap]
    out += [Spacer(1, 10)]
    return out

# ── Header / footer ──────────────────────────────────────────────────────
def on_page(canvas, doc):
    canvas.saveState()
    canvas.setFont('FreeSerif', 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(MARGIN, PAGE_H - 0.60 * inch, C.DOC_TITLE.upper())
    canvas.setStrokeColor(ACCENT)
    canvas.setLineWidth(1.2)
    canvas.line(MARGIN, PAGE_H - 0.70 * inch, PAGE_W - MARGIN, PAGE_H - 0.70 * inch)
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(0.4)
    canvas.line(MARGIN, 0.62 * inch, PAGE_W - MARGIN, 0.62 * inch)
    canvas.setFont('FreeSerif', 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(MARGIN, 0.46 * inch, C.DOC_AUTHOR)
    num = 'i' if doc.page == 1 else str(doc.page - 1)
    canvas.drawRightString(PAGE_W - MARGIN, 0.46 * inch, num)
    canvas.restoreState()

# ── Build story ──────────────────────────────────────────────────────────
story = []

toc = TableOfContents()
toc.levelStyles = [TOC_L0, TOC_L1]
story.append(Paragraph('<b>Table of Contents</b>', TOC_TITLE))
story.append(toc)
story.append(PageBreak())

story.append(Paragraph(md(C.META_NOTE), NOTE))

for sec in C.SECTIONS:
    story.append(CondPageBreak(AVAIL_H * 0.25))
    h1 = add_heading('%s. %s' % (sec['num'], sec['title']), H1, level=0)
    rule = HRFlowable(width='100%', thickness=1.2, color=ACCENT,
                      spaceBefore=0, spaceAfter=12)
    blocks = sec['blocks']
    first = blocks[0]
    if first[0] == 'body':
        story.extend(safe_keep_together([h1, rule, Paragraph(md(first[1]), BODY)]))
        rest = blocks[1:]
    else:
        story.extend(safe_keep_together([h1, rule]))
        rest = blocks
    for kind, payload in ((b[0], b[1]) for b in rest):
        if kind == 'body':
            story.append(Paragraph(md(payload), BODY))
        elif kind == 'h2':
            story.extend(safe_keep_together([add_heading(payload, H2, level=1)]))
        elif kind == 'quote':
            story.extend(quote_block(payload))
        elif kind == 'table':
            story.extend(data_table(payload))
        elif kind == 'note':
            story.append(Paragraph(md(payload), NOTE))

doc = TocDocTemplate(
    OUT_BODY, pagesize=A4,
    leftMargin=MARGIN, rightMargin=MARGIN,
    topMargin=1.05 * inch, bottomMargin=0.95 * inch,
    title=C.DOC_TITLE + ' — ' + 'Trilogy Edition: Critique, Steelman, Survival Test',
    author='Z.ai', creator='Z.ai',
    subject=C.DOC_SUBTITLE,
)
doc.multiBuild(story, onFirstPage=on_page, onLaterPages=on_page)
print('body pdf written:', OUT_BODY)
